# ???? ????Ʈ
# https://kmrho1103.tistory.com/entry/%EC%A0%9C6%EC%9E%A5-%EB%AA%A8%ED%98%95%EB%B9%84%EA%B5%90%ED%8F%89%EA%B0%80-%EC%97%B0%EC%86%8D%ED%98%95-%EB%AA%A9%ED%91%9C%EB%B3%80%EC%88%98?category=700336


install.packages("readr")
library(readr)
weather=read_csv("weatherdata.csv")
weather1=weather[,2:28]
rownames(weather1)=weather$일시
weatherdata=weather1[,1:11]
emotiondata=weather1[,12:27]
rownames(weatherdata)=weather$일시
rownames(emotiondata)=weather$일시
#평균기온,일강수량,평균풍속,평균상대습도,합계일조시간,합계일사,일최심신적설,일최심적설,평균중하층운량,평균지면온도,안개계속시간
#우울,감사,편안,짜증,싫다,불만,피곤,행복,외로움,기쁨,슬픔,공허,고독,답답,분노,질투
emotion=colnames(emotiondata)
#plot(weather)

# 다중회귀분석(단계적 변수선택 : 단계별방법)
weatherdata2=weather[,2:13]
colnames(emotiondata)
class(emotiondata)
emotiondata=as.data.frame(emotiondata)

for(i in 1:length(emotion)){
    capture.output(print(emotion[i]),file=paste("다중회귀분석_",emotion[i],".txt"), append = TRUE)
    capture.output(summary(step(lm(emotiondata[,emotion[i]]~1,data=weather1),scope=list(lower=~1,upper=~평균기온+일강수량+평균풍속+평균상대습도+합계일조시간+합계일사+일최심신적설+일최심적설+평균중하층운량+평균지면온도+안개계속시간),direction="both")),file=paste("다중회귀분석_",emotion[i],".txt"), append = TRUE)
}

pred1=29.49612+weatherdata$평균중하층운량*0.37992+weatherdata$평균지면온도*(-0.53589)+weatherdata$평균기온*0.67737+weatherdata$안개계속시간*(-0.22326)+weatherdata$합계일조시간*1.26221+weatherdata$합계일사*(-0.73339)
capture.output(print("감사 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$감사 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_감사.png",width = 2000, height = 1500)
plot(emotiondata$감사,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=53.0822+weatherdata$평균중하층운량*(-2.0326)+weatherdata$일최심적설*(-0.6160)+weatherdata$평균지면온도*(-0.1838)
capture.output(print("고독 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$고독 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_고독.png",width = 2000, height = 1500)
plot(emotiondata$고독,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=12.84441+weatherdata$평균중하층운량*(-0.08074)+weatherdata$합계일사*(-1.21857)+weatherdata$합계일조시간*1.68572+weatherdata$평균기온*0.41298
capture.output(print("공허 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$공허 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_공허.png",width = 2000, height = 1500)
plot(emotiondata$공허,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=2.08262+weatherdata$평균중하층운량*(-1.03543)+weatherdata$평균상대습도*0.43957+weatherdata$합계일사*(-2.28569)+weatherdata$합계일조시간*3.02602+weatherdata$일최심신적설*(-1.10948)+weatherdata$평균기온*0.40437+weatherdata$평균풍속*2.60077+weatherdata$일강수량*(-0.19501)
capture.output(print("기쁨 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$기쁨 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_기쁨.png",width = 2000, height = 1500)
plot(emotiondata$기쁨,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=34.14286+weatherdata$평균중하층운량*(-0.23087)+weatherdata$합계일사*3.39329+weatherdata$평균지면온도*(-1.16241)+weatherdata$합계일조시간*(-3.91206)+weatherdata$일최심신적설*(-1.26178)
capture.output(print("답답 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$답답 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_답답.png",width = 2000, height = 1500)
plot(emotiondata$답답,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=112.9648+weatherdata$평균중하층운량* 1.3449+weatherdata$합계일사*4.7373+weatherdata$평균상대습도*(-1.0066)+weatherdata$합계일조시간*(-6.6701)
capture.output(print("분노 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$분노 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_분노.png",width = 2000, height = 1500)
plot(emotiondata$분노,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=39.4271+weatherdata$평균중하층운량*(-0.9922)+weatherdata$평균기온*0.4251+weatherdata$평균풍속*2.6115
capture.output(print("불만 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$불만 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_불만.png",width = 2000, height = 1500)
plot(emotiondata$불만,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=67.54103+weatherdata$평균중하층운량 *(-0.34212)+weatherdata$평균상대습도* (-0.32971)+weatherdata$안개계속시간*1.32845
capture.output(print("슬픔 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$슬픔 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_슬픔.png",width = 2000, height = 1500)
plot(emotiondata$슬픔,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=68.9899+weatherdata$평균중하층운량*(-1.7473)+weatherdata$안개계속시간* 2.0265
capture.output(print("싫다 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$싫다 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_싫다.png",width = 2000, height = 1500)
plot(emotiondata$싫다,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=98.3302+weatherdata$평균중하층운량* 1.3053+weatherdata$평균기온*(-1.2731)+weatherdata$일최심적설*0.9548
capture.output(print("외로움 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$외로움 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_외로움.png",width = 2000, height = 1500)
plot(emotiondata$외로움,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=6.28614+weatherdata$평균상대습도*0.43273+weatherdata$안개계속시간*1.26906+weatherdata$평균중하층운량* (-0.27775)+weatherdata$합계일사*0.30433+weatherdata$평균풍속*2.69327
capture.output(print("우울 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$감사 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_우울.png",width = 2000, height = 1500)
plot(emotiondata$우울,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=4.22051+weatherdata$평균상대습도*0.11545+weatherdata$합계일사* (-1.34555)+weatherdata$안개계속시간* (-0.66874)+weatherdata$평균중하층운량*0.13654+weatherdata$평균기온*1.04045+weatherdata$합계일조시간*1.49556+weatherdata$일강수량*(-0.16336)+weatherdata$평균지면온도* (-0.47997)
capture.output(print("질투 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$질투 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_질투.png",width = 2000, height = 1500)
plot(emotiondata$질투,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=9.08185+weatherdata$평균중하층운량*0.27301+weatherdata$평균기온*0.49406+weatherdata$합계일사*(-0.79387)+weatherdata$합계일조시간*1.23018
capture.output(print("짜증 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$짜증 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_짜증.png",width = 2000, height = 1500)
plot(emotiondata$짜증,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=29.49612+weatherdata$평균중하층운량*0.37992+weatherdata$평균지면온도* (-0.53589)+weatherdata$평균기온*0.67737+weatherdata$안개계속시간* (-0.22326)+weatherdata$합계일조시간*1.26221+weatherdata$합계일사* (-0.73339)
capture.output(print("편안 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$편안 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_편안.png",width = 2000, height = 1500)
plot(emotiondata$편안,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=33.50018+weatherdata$평균지면온도*0.38785+weatherdata$평균중하층운량*0.34765
capture.output(print("피곤 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$피곤 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_피곤.png",width = 2000, height = 1500)
plot(emotiondata$피곤,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

pred1=53.12502+weatherdata$평균중하층운량*1.39505+weatherdata$일최심적설*0.74060+weatherdata$합계일사*0.56754+weatherdata$평균풍속*4.59483+weatherdata$안개계속시간* (-1.01175)
capture.output(print("행복 예측 정확도(오차 제곱 평균)"),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
capture.output(mean((emotiondata$행복 - pred1)^2),file=paste("다중회귀분석/다중회귀분석.txt"), append = TRUE)
png("다중회귀분석/다중회귀분석예측_행복.png",width = 2000, height = 1500)
plot(emotiondata$행복,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()


# 상관분석
install.packages("Hmisc")
library(Hmisc)
rcorr(as.matrix(weather1),type="pearson")
rcorr(as.matrix(weather1),type="spearman")



# 시계열분석
install.packages("forecast")
library(forecast)
for(i in 1:length(emotion)){
    emotiondata_ts=ts(emotiondata[,emotion[i]])
    plot(emotiondata_ts)
    # emotiondata_ts.decompose= decompose(emotiondata_ts) 
    emotiondata_ts.diff1=diff(emotiondata_ts, differences = 2)
    # plot(emotiondata_ts.diff1)
    capture.output(auto.arima(emotiondata_ts),file=paste("시계열예측/시계열 예측_",emotion[i],".txt"), append = TRUE)
}

emotiondata_ts=ts(emotiondata$감사)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(5,1,2))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_감사.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$고독)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(4,1,1))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_고독.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$공허)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(0,1,2))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_공허.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$기쁨)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(1,1,1))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_기쁨.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$답답)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(0,1,1))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_답답.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$분노)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(5,1,4))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_분노.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$불만)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(0,1,2))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_불만.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$슬픔)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(1,1,2))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_슬픔.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$싫다)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(0,1,1))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_싫다.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$외로움)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(0,1,1))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_외로움.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$우울)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(0,1,1))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_우울.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$질투)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(5,1,4))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_질투.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$짜증)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(0,1,3))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_짜증.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$편안)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(5,1,2))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_편안.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$피곤)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(0,1,1))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_피곤.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()

emotiondata_ts=ts(emotiondata$행복)
emotiondata_ts.arima=arima(emotiondata_ts, order=c(1,1,1))
emotiondata_ts.forecasts=forecast(emotiondata_ts.arima, h=3)
emotiondata_ts.forecasts
png(paste("시계열예측/시계열예측2_행복.png"),width = 2000, height = 1500)
plot(emotiondata_ts.forecasts)
dev.off()


# 신경망
set.seed(100)
library(neuralnet)
 #-1~1사이 숫자로 변환
max1 = apply(weatherdata, 2, max)
min1 = apply(weatherdata, 2, min)
weatherdata_s = scale(weatherdata,center=min1,scale = max1 - min1) 
weatherdata_s = as.data.frame(weatherdata_s)
max2 = apply(emotiondata, 2, max)
min2 = apply(emotiondata, 2, min)
emotiondata_s = scale(emotiondata,center=min2,scale = max2 - min2) 
emotiondata_s = as.data.frame(emotiondata_s)

nn1 = neuralnet(emotiondata_s$감사~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","평균지면온도","평균기온","안개계속시간","합계일조시간","합계일사")])
pred1 = pred.nn0$net.result*(max(emotiondata$감사)-min(emotiondata$감사))+min(emotiondata$감사)
#head(pred0)
#head(cbind(emotiondata$우울,pred0),50)
capture.output(print("감사 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$감사 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_감사.png",width = 2000, height = 1500)
plot(emotiondata$감사,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$우울~평균상대습도 + 안개계속시간 + 평균중하층운량 + 합계일사 + 평균풍속,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균상대습도","안개계속시간","평균중하층운량","합계일사","평균풍속")])
pred1 = pred.nn0$net.result*(max(emotiondata$우울)-min(emotiondata$우울))+min(emotiondata$우울)
#head(pred0)
#head(cbind(emotiondata$우울,pred0),50)
capture.output(print("우울 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$우울 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_우울.png",width = 2000, height = 1500)
plot(emotiondata$우울,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$편안~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","평균지면온도","평균기온","안개계속시간","합계일조시간","합계일사")])
pred1 = pred.nn0$net.result*(max(emotiondata$편안)-min(emotiondata$편안))+min(emotiondata$편안)
#head(pred0)
#head(cbind(emotiondata$편안,pred0),50)
capture.output(print("편안 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$편안 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_편안.png",width = 2000, height = 1500)
plot(emotiondata$편안,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$짜증~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","평균지면온도","평균기온","안개계속시간","합계일조시간","합계일사")])
pred1 = pred.nn0$net.result*(max(emotiondata$짜증)-min(emotiondata$짜증))+min(emotiondata$짜증)
#head(pred0)
#head(cbind(emotiondata$짜증,pred0),50)
capture.output(print("짜증 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$짜증 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_짜증.png",width = 2000, height = 1500)
plot(emotiondata$짜증,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$싫다~평균중하층운량 + 안개계속시간,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","안개계속시간")])
pred1 = pred.nn0$net.result*(max(emotiondata$싫다)-min(emotiondata$싫다))+min(emotiondata$싫다)
#head(pred0)
#head(cbind(emotiondata$싫다,pred0),50)
capture.output(print("싫다 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$싫다 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_싫다.png",width = 2000, height = 1500)
plot(emotiondata$싫다,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$불만~평균중하층운량 + 평균기온 + 평균풍속,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","평균기온","평균풍속")])
pred1 = pred.nn0$net.result*(max(emotiondata$불만)-min(emotiondata$불만))+min(emotiondata$불만)
#head(pred0)
#head(cbind(emotiondata$불만,pred0),50)
capture.output(print("불만 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$불만 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_불만.png",width = 2000, height = 1500)
plot(emotiondata$불만,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$피곤~평균지면온도 + 평균중하층운량,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균지면온도","평균중하층운량")])
pred1 = pred.nn0$net.result*(max(emotiondata$피곤)-min(emotiondata$피곤))+min(emotiondata$피곤)
#head(pred0)
#head(cbind(emotiondata$피곤,pred0),50)
capture.output(print("피곤 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$피곤 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_피곤.png",width = 2000, height = 1500)
plot(emotiondata$피곤,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$행복~평균중하층운량 + 일최심적설 + 합계일사 + 평균풍속 + 안개계속시간,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","일최심적설","합계일사","평균풍속","안개계속시간")])
pred1 = pred.nn0$net.result*(max(emotiondata$행복)-min(emotiondata$행복))+min(emotiondata$행복)
#head(pred0)
#head(cbind(emotiondata$행복,pred0),50)
capture.output(print("행복 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$행복 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_행복.png",width = 2000, height = 1500)
plot(emotiondata$행복,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$외로움~평균중하층운량 + 평균기온 + 일최심적설,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","평균기온","일최심적설")])
pred1 = pred.nn0$net.result*(max(emotiondata$외로움)-min(emotiondata$외로움))+min(emotiondata$외로움)
#head(pred0)
#head(cbind(emotiondata$외로움,pred0),50)
capture.output(print("외로움 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$외로움 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_외로움.png",width = 2000, height = 1500)
plot(emotiondata$외로움,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$기쁨~평균중하층운량 + 평균상대습도 + 합계일사 + 합계일조시간 + 일최심신적설 + 평균기온 + 평균풍속 + 일강수량,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","평균상대습도","합계일사","합계일조시간","일최심신적설","평균기온","평균풍속","일강수량")])
pred1 = pred.nn0$net.result*(max(emotiondata$기쁨)-min(emotiondata$기쁨))+min(emotiondata$기쁨)
#head(pred0)
#head(cbind(emotiondata$기쁨,pred0),50)
capture.output(print("기쁨 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$기쁨 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_기쁨.png",width = 2000, height = 1500)
plot(emotiondata$기쁨,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$슬픔~평균중하층운량 + 평균상대습도 + 안개계속시간,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","평균상대습도","안개계속시간")])
pred1 = pred.nn0$net.result*(max(emotiondata$슬픔)-min(emotiondata$슬픔))+min(emotiondata$슬픔)
#head(pred0)
#head(cbind(emotiondata$슬픔,pred0),50)
capture.output(print("슬픔 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$슬픔 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_슬픔.png",width = 2000, height = 1500)
plot(emotiondata$슬픔,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$공허~평균중하층운량 + 합계일사 + 합계일조시간 + 평균기온,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","합계일사","합계일조시간","평균기온")])
pred1 = pred.nn0$net.result*(max(emotiondata$공허)-min(emotiondata$공허))+min(emotiondata$공허)
#head(pred0)
#head(cbind(emotiondata$공허,pred0),50)
capture.output(print("공허 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$공허 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_공허.png",width = 2000, height = 1500)
plot(emotiondata$공허,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$고독~평균중하층운량 + 일최심적설 + 평균지면온도,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","일최심적설","평균지면온도")])
pred1 = pred.nn0$net.result*(max(emotiondata$고독)-min(emotiondata$고독))+min(emotiondata$고독)
#head(pred0)
#head(cbind(emotiondata$고독,pred0),50)
capture.output(print("고독 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$고독 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_고독.png",width = 2000, height = 1500)
plot(emotiondata$고독,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$답답~평균중하층운량 + 합계일사 + 평균지면온도 + 합계일조시간 + 일최심신적설,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","합계일사","평균지면온도","합계일조시간","일최심신적설")])
pred1 = pred.nn0$net.result*(max(emotiondata$답답)-min(emotiondata$답답))+min(emotiondata$답답)
#head(pred0)
#head(cbind(emotiondata$답답,pred0),50)
capture.output(print("답답 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$답답 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_답답.png",width = 2000, height = 1500)
plot(emotiondata$답답,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$분노~평균중하층운량 + 합계일사 + 평균상대습도 + 합계일조시간,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균중하층운량","합계일사","평균상대습도","합계일조시간")])
pred1 = pred.nn0$net.result*(max(emotiondata$분노)-min(emotiondata$분노))+min(emotiondata$분노)
#head(pred0)
#head(cbind(emotiondata$분노,pred0),50)
capture.output(print("분노 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$분노 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_분노.png",width = 2000, height = 1500)
plot(emotiondata$분노,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

nn1 = neuralnet(emotiondata_s$질투~평균상대습도 + 합계일사 + 안개계속시간 + 평균중하층운량 + 평균기온 + 합계일조시간 + 일강수량 + 평균지면온도,data=weatherdata_s ,hidden = c(6,4),linear.output = T)
summary(nn1)
plot(nn1)
pred.nn0 = compute(nn1,weatherdata_s[,c("평균상대습도","합계일사","안개계속시간","평균중하층운량","평균기온","합계일조시간","일강수량","평균지면온도")])
pred1 = pred.nn0$net.result*(max(emotiondata$질투)-min(emotiondata$질투))+min(emotiondata$질투)
#head(pred0)
#head(cbind(emotiondata$질투,pred0),50)
capture.output(print("질투 예측 정확도(오차 제곱 평균)"),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
capture.output(mean((emotiondata$질투 - pred1)^2),file=paste("신경망모형/신경망모형.txt"), append = TRUE)
png("신경망모형/신경망모형예측_질투.png",width = 2000, height = 1500)
plot(emotiondata$질투,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

# 의사결정나무
# rpart
library(rpart)
emotiondata.control<-rpart.control(xval=10,cp=0,minsplit=nrow(weatherdata)*0.05)
emotiondata.fit=rpart(emotiondata$우울~평균상대습도 + 안개계속시간 + 평균중하층운량 + 합계일사 + 평균풍속, data=weatherdata, method="anova", control=emotiondata.control)
emotiondata.fit
printcp(emotiondata.fit)
names(emotiondata.fit)
which.min(emotiondata.fit$cp[,4])
which.min(emotiondata.fit$cptable[,'xerror'])
emotiondata.fit$cptable[which.min(emotiondata.fit$cptable[,'xerror'])]
emotiondata.fit$cptable[which.min(emotiondata.fit$cptable[,'xerror']),]
emotiondata.fit.prune<-prune(emotiondata.fit,cp=emotiondata.fit$cptable[which.min(emotiondata.fit$cptable[,'xerror'])])
emotiondata.fit.prune
emotiondata.fit.prune$variable.importance
plot(emotiondata.fit.prune,uniform=T,margin=0.1)
text(emotiondata.fit.prune,use.n=T,col='blue',cex=0.7)
pre=predict(emotiondata.fit.prune,newdata=weatherdata,type='vector')
mean((emotiondata$우울 - pre)^2)
plot(emotiondata$우울,pre,xlab='Observed values',ylab='Fitted values',xlim=c(0,100),ylim=c(0,100))
abline(0,1)

#ctree
install.packages("party")
library(party)

tree=ctree(emotiondata$우울~평균상대습도 + 안개계속시간 + 평균중하층운량 + 합계일사 + 평균풍속, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_우울.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("우울 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$우울 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_우울.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$감사~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_감사.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("감사 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$감사 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_감사.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$편안~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_편안.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("편안 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$편안 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_편안.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$짜증~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_짜증.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("짜증 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$짜증 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_짜증.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$싫다~평균중하층운량 + 안개계속시간, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_싫다.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("싫다 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$싫다 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_싫다.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$불만~평균중하층운량 + 평균기온 + 평균풍속, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_불만.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("불만 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$불만 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_불만.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$피곤~평균지면온도 + 평균중하층운량, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_피곤.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("피곤 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$피곤 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_피곤.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$행복~평균중하층운량 + 일최심적설 + 합계일사 + 평균풍속 + 안개계속시간, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_행복.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("행복 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$행복 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_행복.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$외로움~평균중하층운량 + 평균기온 + 일최심적설, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_외로움.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("외로움 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$외로움 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_외로움.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$기쁨~평균중하층운량 + 평균상대습도 + 합계일사 + 합계일조시간 + 일최심신적설 + 평균기온 + 평균풍속 + 일강수량, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_기쁨.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("기쁨 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$기쁨 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_기쁨.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$우울~평균중하층운량 + 평균상대습도 + 안개계속시간, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_슬픔.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("슬픔 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$우울 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_슬픔.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$공허~평균중하층운량 + 합계일사 + 합계일조시간 + 평균기온, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_공허.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("공허 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$우울 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_공허.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$고독~평균중하층운량 + 일최심적설 + 평균지면온도, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_고독.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("고독 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$고독 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_고독.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$답답~평균중하층운량 + 합계일사 + 평균지면온도 + 합계일조시간 + 일최심신적설, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_답답.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("답답 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$답답 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_답답.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$분노~평균중하층운량 + 합계일사 + 평균상대습도 + 합계일조시간, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_분노.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("분노 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$분노 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_분노.png",width = 2000, height = 1500)
plot(tree)
dev.off()

tree=ctree(emotiondata$질투~평균상대습도 + 합계일사 + 안개계속시간 + 평균중하층운량 + 평균기온 + 합계일조시간 + 일강수량 + 평균지면온도, data=weatherdata)
capture.output(tree,file=paste("의사결정나무/의사결정나무_질투.txt"), append = TRUE)
cpre=predict(tree,data=weatherdata)
capture.output(print("질투 예측 정확도(오차 제곱 평균)"),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
capture.output(mean((emotiondata$질투 - cpre)^2),file=paste("의사결정나무/의사결정나무.txt"), append = TRUE)
png("의사결정나무/의사결정나무_질투.png",width = 2000, height = 1500)
plot(tree)
dev.off()

# mean((emotiondata$우울 - cpre)^2) # 제곱 평균 오차

# 랜덤포레스트
# randomForest
install.packages("randomForest")
library(randomForest)
rf<-randomForest(emotiondata$우울~평균상대습도 + 안개계속시간 + 평균중하층운량 + 합계일사 + 평균풍속,data=weatherdata,ntree=500,importance=T,na.action=na.omit)
importance(rf,type=1)
rpre= predict(rf,newdata=weatherdata)
rpre
mean((emotiondata$우울 - rpre)^2)
plot(emotiondata$우울,rpre,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)

# cforest
set.seed(1234)
cf=cforest(emotiondata$우울~평균상대습도 + 안개계속시간 + 평균중하층운량 + 합계일사 + 평균풍속,data=weatherdata)
cf.pre=predict(cf, newdata=weatherdata)
mean((emotiondata$우울 - cf.pre)^2)
plot(emotiondata$우울,cf.pre,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)

cf = cforest(emotiondata$감사~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("감사 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$감사 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_감사.png",width = 2000, height = 1500)
plot(emotiondata$감사,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$우울~평균상대습도 + 안개계속시간 + 평균중하층운량 + 합계일사 + 평균풍속,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("우울 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$감사 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_우울.png",width = 2000, height = 1500)
plot(emotiondata$우울,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$편안~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("편안 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$편안 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_편안.png",width = 2000, height = 1500)
plot(emotiondata$편안,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$짜증~평균중하층운량 + 평균지면온도 + 평균기온 + 안개계속시간 + 합계일조시간 + 합계일사,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("짜증 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$짜증 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_짜증.png",width = 2000, height = 1500)
plot(emotiondata$짜증,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()


cf = cforest(emotiondata$싫다~평균중하층운량 + 안개계속시간,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("싫다 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$싫다 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_싫다.png",width = 2000, height = 1500)
plot(emotiondata$싫다,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$불만~평균중하층운량 + 평균기온 + 평균풍속,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("불만 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$불만 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_불만.png",width = 2000, height = 1500)
plot(emotiondata$불만,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$피곤~평균지면온도 + 평균중하층운량,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("피곤 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$피곤 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_피곤.png",width = 2000, height = 1500)
plot(emotiondata$피곤,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$행복~평균중하층운량 + 일최심적설 + 합계일사 + 평균풍속 + 안개계속시간,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("행복 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$행복 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_행복.png",width = 2000, height = 1500)
plot(emotiondata$행복,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$외로움~평균중하층운량 + 평균기온 + 일최심적설,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("외로움 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$외로움 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_외로움.png",width = 2000, height = 1500)
plot(emotiondata$외로움,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$기쁨~평균중하층운량 + 평균상대습도 + 합계일사 + 합계일조시간 + 일최심신적설 + 평균기온 + 평균풍속 + 일강수량,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("기쁨 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$기쁨 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_기쁨.png",width = 2000, height = 1500)
plot(emotiondata$기쁨,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$슬픔~평균중하층운량 + 평균상대습도 + 안개계속시간,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("슬픔 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$슬픔 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_슬픔.png",width = 2000, height = 1500)
plot(emotiondata$슬픔,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$공허~평균중하층운량 + 합계일사 + 합계일조시간 + 평균기온,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("공허 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$공허 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_공허.png",width = 2000, height = 1500)
plot(emotiondata$공허,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$고독~평균중하층운량 + 일최심적설 + 평균지면온도,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("고독 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$고독 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_고독.png",width = 2000, height = 1500)
plot(emotiondata$고독,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$답답~평균중하층운량 + 합계일사 + 평균지면온도 + 합계일조시간 + 일최심신적설,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("답답 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$답답 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_답답.png",width = 2000, height = 1500)
plot(emotiondata$답답,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$분노~평균중하층운량 + 합계일사 + 평균상대습도 + 합계일조시간,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("분노 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$분노 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_분노.png",width = 2000, height = 1500)
plot(emotiondata$분노,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()

cf = cforest(emotiondata$질투~평균상대습도 + 합계일사 + 안개계속시간 + 평균중하층운량 + 평균기온 + 합계일조시간 + 일강수량 + 평균지면온도,data=weatherdata)
pred1 = predict(cf, newdata=weatherdata)
capture.output(print("질투 예측 정확도(오차 제곱 평균)"),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
capture.output(mean((emotiondata$질투 - pred1)^2),file=paste("랜덤포레스트/랜덤포레스트.txt"), append = TRUE)
png("랜덤포레스트/랜덤포레스트예측_질투.png",width = 2000, height = 1500)
plot(emotiondata$질투,pred1,xlab='Observed Values',ylab='Fitted Values')
abline(0,1)
dev.off()


